WHENEVER SQLERROR EXIT 1;
WHENEVER OSERROR EXIT 1;

CONNECT / AS SYSDBA

PROMPT Create role DBMS_PARTITION_WRANGLER_ADMIN to permit users to manage their partitions
CREATE ROLE DBMS_PARTITION_WRANGLER_ADMIN;

PROMPT Create role DBMS_PARTITION_WRANGLER_ADMIN to permit users to view partition status
CREATE ROLE DBMS_PARTITION_WRANGLER_VIEWER;
